### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by darwinyip** [google-developer-training/android-basics-kotlin-words-app#203]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-fragments-navigation-component#8

**In which task and step of the codelab can this issue be found?**
Last step when running.

**Describe the problem**
Navigating to WordListFragment gives a black screen and fails to go up.

**Steps to reproduce?**
1. Open app
2. Click on any letter
3. See black screen

**Versions**
_Android Studio version:_ Android Studio Arctic Fox | 2020.3.1 Patch 3

_API version of the emulator:_ API 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![Screenshot from 2021-10-27 23-54-22](https://user-images.githubusercontent.com/3499338/139183952-94fb2ead-436c-42f8-bd56-f679b45e7b32.png)

**Comment by osuleymanova** [comment]
@darwinyip 
Thank you for reaching out to us. In order to help you with troubleshooting, we need to review the code snippet with the error. First we recommend to update your Android Studio version, then download the recently updated code and follow the steps provided in the codelab. If the error happens again, feel free to reopen the ticket. 
Happy coding!
