### ISSUE TITLE
Android Basics: Collections

### ISSUE THREAD

**Issue by eugenegrib** [google-developer-training/android-basics-kotlin-words-app#245]
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**
в OnClickListener и OnKeyListener в Android приведен пример с использованием java кода

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment]
@eugenegrib 
Please provide the required details when reporting an issue(URL of codelab, in which task and step of the codelab can this issue be found?) so that we can help you with troubleshooting or fix the issue on our side. It's good to include the screenshot or code snippet where the issue occurs.

**Comment by osuleymanova** [comment]
Closing this issue, since there is no issue description.
Please create a new one, if you need help.
All the best learning Android.
