### ISSUE TITLE
Android Basics: Fragments Navigation component: incorrect explanation of get()

### ISSUE THREAD

**Issue by inhaledesign** [google-developer-training/android-basics-kotlin-words-app#299]
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component

**In which task and step of the codelab can this issue be found?**
Implement LetterListFragment

**Describe the problem**
`private val binding get() = _binding!!`
"Here, get() means this property is "get-only". That means you can get the value, but once assigned (as it is here), you can't assign it to something else."

This is incorrect or very unclear. It reads like `get()` flags this property as immutable.

`val` is what makes this property immutable.  `get() =` is defining a getter for the `binding` property that returns `binding!!`.

Please refer to https://kotlinlang.org/docs/properties.html#getters-and-setters

**Comment by Sonofasleep** [comment]
I agree, it is very confusing. Would be cool to add some more explanation on this.

To explain that you may catch an error:
androidx.fragment.app.Fragment$InstantiationException

Because your binding is null without getter. 
Because with ` get() ` your  `binding` will be calling `_binding` every time it's acessed. (It will "see" changes in `_binding` in another words.)
