### ISSUE TITLE
Android Basics: Cuestionarios

### ISSUE THREAD

**Issue by flaco1990** [google-developer-training/android-basics-kotlin-words-app#324]
Cuando quiero realizar los cuestionarios del curso, me da error al querer enviar los resultados y no los registra.

**Comment by osuleymanova** [comment]
@flaco1990 
Please provide the required details (codelab URL, steps, screenshots, etc...) while reporting an issue so that we can help you with troubleshooting.
Proporcione los detalles requeridos (URL de codelab, pasos, capturas de pantalla, etc...) al informar de un problema para que podamos ayudarle a solucionarlo.

**Comment by softdevandre** [comment]
> @flaco1990 Please provide the required details (codelab URL, steps, screenshots, etc...) while reporting an issue so that we can help you with troubleshooting. Proporcione los detalles requeridos (URL de codelab, pasos, capturas de pantalla, etc...) al informar de un problema para que podamos ayudarle a solucionarlo.

Hi, @osuleymanova
I'm having exactly the same issue, not just in this codelab but on all codelabs from the developers platform.
I even had opened an issue on the issue tracker (almost six months by now already) to see if someone could help me and provide some clear answer on why I couldn't complete any quizzes or getting new badges, and it seems there's no clear answer yet. 
This is making it impossible for me to complete any course from the platform.
Here's the issue tracker link: https://issuetracker.google.com/issues/231691464

If you have some glimpse on what could be happening, please, I'll be very glad to know.
Thanks in advance.

**Comment by osuleymanova** [comment]
@softdevandre 
Thank you for your reply and the issue tracker link provided. We are still investigating your issue. There is no clear understanding, probably something went wrong in your profile settings.
As for your developer's profile, we didn't find any messages such as "You haven't completed any pathways or codelabs yet. Once you have, we will update your progress here. The service is currently unavailable." Please refer to the screenshot below:

<img width="1602" alt="Screen Shot 2022-10-26 at 4 19 22 PM" src="https://user-images.githubusercontent.com/86437155/198157267-f8a8ec83-77d3-44e4-95e0-ec471679d443.png">

We appreciate if you would keep in touch with us until your issue is solved. Our apologies for any inconvenience caused.

**Comment by softdevandre** [comment]
@osuleymanova 
Thank you so much for your reply!
That's very weird. So, you can see my profile as normal, but when I try to access, it does show the message you pointed out.
I've posted screenshots on how I'm seeing this, as you can refer in the thread from the issue tracker link that I've provided.
What settings do you mean? The ones which I can manage after my profile is created or the ones from the system while creating my profile? 
Anyway, I'm having this problem with the badges, but also it's happening that I couldn't finish any codelab due a error that just occur when I choose the right answer enough to pass a the test. As I can see that's problably the main problem as I cannot finish any codelab without finishing a quiz.
When I inpected both pages with the issues mentioned above, it does throws two errors status response code: 503 and 403.
What grabbed my attention specifically was the 403 error which has the following status message: "PERMISSION DENIED", within the reason: "API_KEY_HTTP_REFERRER_BLOCKED". I wonder what's possibly causing this denying, as I've searched through the issue tracker and several developers are having the same issue and with the same error response.

Is there something that you suggest that I could try in my settings or any other possible solution for this?
Thanks again and I'll surely keep in touch until it's solved.

**Comment by softdevandre** [comment]
Hello, @osuleymanova and @flaco1990.
Someone helped me to find out a temporary solution for this.
The problem is doubtless something involving location permission. Someone from Brazil (where I'm also located) had the same problem and told me in the issue tracker that as changing the location to USA through a VPN service, we could see the profile with all the badges earned included and I also tested finish the quizzes and it went all normal.
So it seems that for someone located outside USA (or perhaps a limited number of countries) isn't being allowed to visualize correctly the profile with the badges nor completing the codelabs.
I'll use in meanwhile a VPN service to change my location to USA in order to finish the codelabs, but I'll be waiting for a fix from the staff team.

**Comment by osuleymanova** [comment]
Hello @softdevandre,

Thanks for reaching out to us and sharing your feedback. Hopefully it helps someone.
