### ISSUE TITLE
Android Basics: Fragments Navigation component

### ISSUE THREAD

**Issue by shalalaMursaliyeva** [google-developer-training/android-basics-kotlin-words-app#356]
**URL of codelab**    
https://developer.android.com/codelabs/basic-android-kotlin-training-fragments-navigation-component?hl=en#1

**In which task and step of the codelab can this issue be found?**
cloning app from github

**Describe the problem**
We have to create fragments on our own, but the link is given to github, when i clone it , i already see the fragments 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by shalva97** [comment]
Also had same issue. The picture they have is missleading, because it shows `main` branch and says `Module name with starter code: activities`. I tried to cloned the repo, checked out main branch and started looking for `activities` module, which was not there.

As I understood, `main` branch containes completed codelab and a branch called `activities` contains starting code. 

TL;DL use `activities` branch:

![Screenshot 2023-08-23 at 16 21 32](https://github.com/google-developer-training/android-basics-kotlin-words-app/assets/22417494/be3c5c4d-8a6d-4894-9b82-89d58f054d48)
